name: Tests

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  tests:
    name: "PHP Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: "8.2"
            composer-deps: latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.composer-deps }}-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.composer-deps }}"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --ignore-platform-reqs"

      - name: "Run code style check"
        run: "composer cs"

      - name: "Run test"
        run: "composer test"
